// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ZeroFormatter.CodeGenerator
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class InitializerGenerator : InitializerGeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("#pragma warning disable 618\r\n#pragma warning disable 612\r\n#pragma warning disable" +
                    " 414\r\n#pragma warning disable 168\r\nnamespace ");
            
            #line 10 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write(@"
{
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::ZeroFormatter.Formatters;
    using global::ZeroFormatter.Internal;
    using global::ZeroFormatter.Segments;
    using global::ZeroFormatter.Comparers;

    public static partial class ZeroFormatterInitializer
    {
        static bool registered = false;

");
            
            #line 24 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
 if( !UnuseUnityAttribute) { 
            
            #line default
            #line hidden
            this.Write("        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeL" +
                    "oadType.BeforeSceneLoad)]\r\n");
            
            #line 26 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        public static void Register()\r\n        {\r\n            if(registered) retu" +
                    "rn;\r\n            registered = true;\r\n");
            
            #line 31 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"

   var resolverName = (ForceDefaultResolver) ? "ZeroFormatter.Formatters.DefaultResolver" : ResolverName;
   var resolverNameGenericArg = (ForceDefaultResolver) ? "" : "<" + ResolverName + ">";

            
            #line default
            #line hidden
            this.Write("            // Enums\r\n");
            
            #line 36 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
 foreach(var g in Enums) { foreach(var t in g.Types) {   
            
            #line default
            #line hidden
            this.Write("            ZeroFormatter.Formatters.Formatter<");
            
            #line 37 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resolverName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 37 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(t.FullName));
            
            #line default
            #line hidden
            this.Write(">.Register(new ");
            
            #line 37 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(g.Namespace + "." + t.Name));
            
            #line default
            #line hidden
            this.Write("Formatter");
            
            #line 37 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resolverNameGenericArg));
            
            #line default
            #line hidden
            this.Write("());\r\n");
            
            #line 38 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
 if(t.IsGenerateEqualityComparer) { 
            
            #line default
            #line hidden
            this.Write("            ZeroFormatter.Comparers.ZeroFormatterEqualityComparer<");
            
            #line 39 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(t.FullName));
            
            #line default
            #line hidden
            this.Write(">.Register(new ");
            
            #line 39 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(g.Namespace + "." + t.Name));
            
            #line default
            #line hidden
            this.Write("EqualityComparer());\r\n");
            
            #line 40 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
 } 
            
            #line default
            #line hidden
            
            #line 41 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
 if (t.IncludeNullable) { 
            
            #line default
            #line hidden
            this.Write("            ZeroFormatter.Formatters.Formatter<");
            
            #line 42 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resolverName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 42 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(t.FullName));
            
            #line default
            #line hidden
            this.Write("?>.Register(new ");
            
            #line 42 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(g.Namespace + ".Nullable" + t.Name));
            
            #line default
            #line hidden
            this.Write("Formatter");
            
            #line 42 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resolverNameGenericArg));
            
            #line default
            #line hidden
            this.Write("());\r\n");
            
            #line 43 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
 if(t.IsGenerateEqualityComparer) { 
            
            #line default
            #line hidden
            this.Write("            ZeroFormatter.Comparers.ZeroFormatterEqualityComparer<");
            
            #line 44 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(t.FullName));
            
            #line default
            #line hidden
            this.Write("?>.Register(new NullableEqualityComparer<");
            
            #line 44 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(t.FullName));
            
            #line default
            #line hidden
            this.Write(">());\r\n");
            
            #line 45 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
 } 
            
            #line default
            #line hidden
            
            #line 46 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            \r\n");
            
            #line 48 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
 } } 
            
            #line default
            #line hidden
            this.Write("            // Objects\r\n");
            
            #line 50 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
 foreach(var g in Objects) { foreach(var t in g.Types) {   
            
            #line default
            #line hidden
            this.Write("            ZeroFormatter.Formatters.Formatter<");
            
            #line 51 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resolverName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 51 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(t.FullName));
            
            #line default
            #line hidden
            this.Write(">.Register(new ");
            
            #line 51 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(g.Namespace + "." + t.Name));
            
            #line default
            #line hidden
            this.Write("Formatter");
            
            #line 51 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resolverNameGenericArg));
            
            #line default
            #line hidden
            this.Write("());\r\n");
            
            #line 52 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
 } } 
            
            #line default
            #line hidden
            this.Write("            // Structs\r\n");
            
            #line 54 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
 foreach(var g in Structs) { foreach(var t in g.Types) {   
            
            #line default
            #line hidden
            this.Write("            {\r\n                var structFormatter = new ");
            
            #line 56 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(g.Namespace + "." + t.Name));
            
            #line default
            #line hidden
            this.Write("Formatter");
            
            #line 56 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resolverNameGenericArg));
            
            #line default
            #line hidden
            this.Write("();\r\n                ZeroFormatter.Formatters.Formatter<");
            
            #line 57 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resolverName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 57 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(t.FullName));
            
            #line default
            #line hidden
            this.Write(">.Register(structFormatter);\r\n                ZeroFormatter.Formatters.Formatter<" +
                    "");
            
            #line 58 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resolverName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 58 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(t.FullName));
            
            #line default
            #line hidden
            this.Write("?>.Register(new global::ZeroFormatter.Formatters.NullableStructFormatter<");
            
            #line 58 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resolverName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 58 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(t.FullName));
            
            #line default
            #line hidden
            this.Write(">(structFormatter));\r\n            }\r\n");
            
            #line 60 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
 } } 
            
            #line default
            #line hidden
            this.Write("            // Unions\r\n");
            
            #line 62 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
 foreach(var g in Unions) { foreach(var t in g.Types) {   
            
            #line default
            #line hidden
            this.Write("            {\r\n                var unionFormatter = new ");
            
            #line 64 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(g.Namespace + "." + t.Name));
            
            #line default
            #line hidden
            this.Write("Formatter");
            
            #line 64 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resolverNameGenericArg));
            
            #line default
            #line hidden
            this.Write("();\r\n                ZeroFormatter.Formatters.Formatter<");
            
            #line 65 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resolverName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 65 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(t.FullName));
            
            #line default
            #line hidden
            this.Write(">.Register(unionFormatter);\r\n            }\r\n");
            
            #line 67 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
 } } 
            
            #line default
            #line hidden
            this.Write("            // Generics\r\n");
            
            #line 69 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
 foreach(var g in GenericTypes) { 
            
            #line default
            #line hidden
            
            #line 70 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
 if (g.TypeKind == GenericTypeKind.KeyTuple) { 
            
            #line default
            #line hidden
            this.Write("            ZeroFormatter.Formatters.Formatter.RegisterKeyTuple<");
            
            #line 71 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resolverName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 71 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(g.ElementTypes));
            
            #line default
            #line hidden
            this.Write(">();\r\n");
            
            #line 72 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
 } else if(g.TypeKind == GenericTypeKind.List) { 
            
            #line default
            #line hidden
            this.Write("            ZeroFormatter.Formatters.Formatter.RegisterList<");
            
            #line 73 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resolverName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 73 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(g.ElementTypes));
            
            #line default
            #line hidden
            this.Write(">();\r\n");
            
            #line 74 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
 } else if(g.TypeKind == GenericTypeKind.Array) { 
            
            #line default
            #line hidden
            this.Write("            ZeroFormatter.Formatters.Formatter.RegisterArray<");
            
            #line 75 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resolverName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 75 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(g.ElementTypes));
            
            #line default
            #line hidden
            this.Write(">();\r\n");
            
            #line 76 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
 } else if(g.TypeKind == GenericTypeKind.Collection) { 
            
            #line default
            #line hidden
            this.Write("            ZeroFormatter.Formatters.Formatter.RegisterCollection<");
            
            #line 77 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resolverName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 77 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(g.ElementTypes));
            
            #line default
            #line hidden
            this.Write(">();\r\n");
            
            #line 78 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
 } else if(g.TypeKind == GenericTypeKind.ReadOnlyList) { 
            
            #line default
            #line hidden
            this.Write("            ZeroFormatter.Formatters.Formatter.RegisterReadOnlyList<");
            
            #line 79 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resolverName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 79 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(g.ElementTypes));
            
            #line default
            #line hidden
            this.Write(">();\r\n");
            
            #line 80 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
 } else if(g.TypeKind == GenericTypeKind.Dictionary) { 
            
            #line default
            #line hidden
            this.Write("            ZeroFormatter.Formatters.Formatter.RegisterDictionary<");
            
            #line 81 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resolverName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 81 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(g.ElementTypes));
            
            #line default
            #line hidden
            this.Write(">();\r\n");
            
            #line 82 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
 } else if(g.TypeKind == GenericTypeKind.LazyDictionary) { 
            
            #line default
            #line hidden
            this.Write("            ZeroFormatter.Formatters.Formatter.RegisterLazyDictionary<");
            
            #line 83 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resolverName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 83 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(g.ElementTypes));
            
            #line default
            #line hidden
            this.Write(">();\r\n");
            
            #line 84 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
 } else if(g.TypeKind == GenericTypeKind.LazyReadOnlyDictionary) { 
            
            #line default
            #line hidden
            this.Write("            ZeroFormatter.Formatters.Formatter.RegisterLazyReadOnlyDictionary<");
            
            #line 85 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resolverName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 85 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(g.ElementTypes));
            
            #line default
            #line hidden
            this.Write(">();\r\n");
            
            #line 86 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
 } else if(g.TypeKind == GenericTypeKind.Lookup) { 
            
            #line default
            #line hidden
            this.Write("            ZeroFormatter.Formatters.Formatter.RegisterLookup<");
            
            #line 87 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resolverName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 87 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(g.ElementTypes));
            
            #line default
            #line hidden
            this.Write(">();\r\n");
            
            #line 88 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
 } else if(g.TypeKind == GenericTypeKind.InterfaceCollection) { 
            
            #line default
            #line hidden
            this.Write("            ZeroFormatter.Formatters.Formatter.RegisterInterfaceCollection<");
            
            #line 89 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resolverName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 89 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(g.ElementTypes));
            
            #line default
            #line hidden
            this.Write(">();\r\n");
            
            #line 90 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
 } else if(g.TypeKind == GenericTypeKind.Enumerable) { 
            
            #line default
            #line hidden
            this.Write("            ZeroFormatter.Formatters.Formatter.RegisterEnumerable<");
            
            #line 91 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resolverName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 91 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(g.ElementTypes));
            
            #line default
            #line hidden
            this.Write(">();\r\n");
            
            #line 92 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
 } else if(g.TypeKind == GenericTypeKind.ReadOnlyCollection) { 
            
            #line default
            #line hidden
            this.Write("            ZeroFormatter.Formatters.Formatter.RegisterReadOnlyCollection<");
            
            #line 93 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resolverName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 93 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(g.ElementTypes));
            
            #line default
            #line hidden
            this.Write(">();\r\n");
            
            #line 94 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
 } else if(g.TypeKind == GenericTypeKind.KeyValuePair) { 
            
            #line default
            #line hidden
            this.Write("            ZeroFormatter.Formatters.Formatter.RegisterKeyValuePair<");
            
            #line 95 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resolverName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 95 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(g.ElementTypes));
            
            #line default
            #line hidden
            this.Write(">();\r\n");
            
            #line 96 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
 } else if(g.TypeKind == GenericTypeKind.LazyLookup) { 
            
            #line default
            #line hidden
            this.Write("            ZeroFormatter.Formatters.Formatter.RegisterLazyLookup<");
            
            #line 97 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(resolverName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 97 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(g.ElementTypes));
            
            #line default
            #line hidden
            this.Write(">();\r\n");
            
            #line 98 "C:\Users\y.kawai\Documents\neuecc\ZeroFormatter\src\ZeroFormatter.CodeGenerator\InitializerGenerator.tt"
 } } 
            
            #line default
            #line hidden
            this.Write("        }\r\n    }\r\n}\r\n#pragma warning restore 168\r\n#pragma warning restore 414\r\n#p" +
                    "ragma warning restore 618\r\n#pragma warning restore 612");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class InitializerGeneratorBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
